# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brickdiff < Formula
  desc ""
  homepage ""
  version "0.3.2"
  license "GPL3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Geekgasm/brickdiff/releases/download/v0.3.2/brickdiff_0.3.2_Darwin_arm64.zip"
      sha256 "186d380915fd67422251a02d8436f80710fd2909321bb6a4d7fadcd7bee23241"

      def install
        bin.install "brickdiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Geekgasm/brickdiff/releases/download/v0.3.2/brickdiff_0.3.2_Darwin_x86_64.zip"
      sha256 "8b6ee6e68c1e183f7c9d3b95118496f82d1dfc6538b871f3c23a86edd9706555"

      def install
        bin.install "brickdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Geekgasm/brickdiff/releases/download/v0.3.2/brickdiff_0.3.2_Linux_arm64.zip"
      sha256 "7c0ba7ff5f734447d41d6eb84f5616fecba2350247f1086b739ae7bd307467d7"

      def install
        bin.install "brickdiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Geekgasm/brickdiff/releases/download/v0.3.2/brickdiff_0.3.2_Linux_x86_64.zip"
      sha256 "5a70b69cefd2303b8b4e74ed11c3ea3e91a50376f90469438e28045f6e218ebc"

      def install
        bin.install "brickdiff"
      end
    end
  end
end
